### ISSUE TITLE
No such file or directory: /tmp/tmpXXXXX/inference.yaml

### ISSUE THREAD

**Issue by missEldgard** [damian0815/grate#1]
Hi, when I run the following, I get an error that it doesn't find the inference yaml. I couldn't find a way to specify it, it is located at the same location where I run my command, v1-inference.yaml. I am currently using the EveryDream runpod image. Using `--local_files_only` didn't fix the problem, in case it was trying to download the model and store it in `/tmp/`. The "demo" folder indeed exist (output path).

Here is the command : 

```
grate --prompts \
"test" \
--repo_ids_or_paths \
"./myModel.ckpt" \
--output_path ./demo/grate-demo.png
```

output :

```
1 prompts
  0%|                                                                                    | 0/1 [00:00<?, ?it/s]model ./sd1_eldgard21-ep60-gs22860.ckpt:
global_step key not found in model
  0%|                                                                                    | 0/1 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/venv/bin/grate", line 8, in <module>
    sys.exit(main())
  File "/workspace/venv/lib/python3.10/site-packages/sdgrate/grate.py", line 474, in main
    render_all(prompts=prompts,
  File "/workspace/venv/lib/python3.10/site-packages/sdgrate/grate.py", line 330, in render_all
    pipeline = load_model(repo_id_or_path, local_files_only=local_files_only)
  File "/workspace/venv/lib/python3.10/site-packages/sdgrate/grate.py", line 152, in load_model
    return load_pipeline_from_original_stable_diffusion_ckpt(repo_id_or_path)
  File "/workspace/venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1014, in load_pipeline_from_original_stable_diffusion_ckpt
    original_config = OmegaConf.load(original_config_file)
  File "/workspace/venv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 187, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpnjn0_ctg/inference.yaml'
```

**Comment by missEldgard** [comment]
I was using .ckpt instead of diffuser format
